-- Insert houses
INSERT INTO HOUSE (HOUSEKEY, FOUNDER, NAME, REGION)VALUES ('STR', 'Brandon the Builder', 'House Stark', 'The North');

INSERT INTO HOUSE (HOUSEKEY, FOUNDER, NAME, REGION)VALUES ('LNN', 'Lann the Clever', 'House Lannister', 'The Westerlands');

INSERT INTO HOUSE (HOUSEKEY, FOUNDER, NAME, REGION)VALUES ('TRG', 'Aegon the Conqueror', 'House Targaryen', 'Dragonstone');

INSERT INTO HOUSE (HOUSEKEY, FOUNDER, NAME, REGION)VALUES ('MRT', 'Nymeria', 'House Martell', 'Dorne');


-- Insert characters
INSERT INTO CHARACTER (CHARACTERKEY, BIRTHPLACE, NAME, SKILLLEVEL, WEAPON, HOUSE_HOUSEKEY)VALUES ('NED', 'Winterfell', 'Eddard Stark', 85, 'Greatsword', 'STR');

INSERT INTO CHARACTER (CHARACTERKEY, BIRTHPLACE, NAME, SKILLLEVEL, WEAPON, HOUSE_HOUSEKEY)VALUES ('JAI', 'Casterly Rock', 'Jaime Lannister', 90, 'Sword', 'LNN');

INSERT INTO CHARACTER (CHARACTERKEY, BIRTHPLACE, NAME, SKILLLEVEL, WEAPON, HOUSE_HOUSEKEY)VALUES ('DAN', 'Dragonstone', 'Daenerys Targaryen', 80, 'Dragons', 'TRG');

INSERT INTO CHARACTER (CHARACTERKEY, BIRTHPLACE, NAME, SKILLLEVEL, WEAPON, HOUSE_HOUSEKEY)VALUES ('OBE', 'Sunspear', 'Oberyn Martell', 95, 'Spear', 'MRT');


-- Insert bouts
INSERT INTO BOUT (BOUTKEY, ATTACKERPOINTS, DEFENDERPOINTS, TOURNEY, ATTACKER_CHARACTERKEY, DEFENDER_CHARACTERKEY)VALUES ('BOUT01', 15, 10, 'Winter Tourney', 'NED', 'JAI');

INSERT INTO BOUT (BOUTKEY, ATTACKERPOINTS, DEFENDERPOINTS, TOURNEY, ATTACKER_CHARACTERKEY, DEFENDER_CHARACTERKEY)VALUES ('BOUT02', 12, 8, 'Spring Tourney', 'DAN', 'OBE');